var num1 = 5.2;
var num2 = 7.1;
var num3 = 900;
var num4 = -1;
var str1 = "hello";
var str2 = "goodbye";
var str3 = "I am coding!";
var bool1 = true;
var bool2 = 2 < 1;
var undef;
console.log("The First Number: " + num1);
console.log("The Second Number: " + num2);
console.log("The Third Number: " + num3);
console.log("The Fourth Number: " + num4);
console.log("The First String: " + str1);
console.log("The Second String: " + str2);
console.log("The Third String: " + str3);
console.log("The First Boolean: " + bool1);
console.log("The Second Boolean: " + bool2);
console.log("The Undefined Variable: + undef");
